/* Generated By:JJTree: Do not edit this line. ASTbranchLink.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTbranchLink extends SimpleNode {
  public ASTbranchLink(int id) {
    super(id);
  }

  public ASTbranchLink(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a2a270714ffda3678c6f68a0bc3c4356 (do not edit this line) */
