/* Generated By:JJTree: Do not edit this line. ASTcloseAUp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTcloseAUp extends SimpleNode {
  public ASTcloseAUp(int id) {
    super(id);
  }

  public ASTcloseAUp(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d209e4790e7d81e878deada34ceb3c88 (do not edit this line) */
