/* Generated By:JJTree: Do not edit this line. ASTcloseAUp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTcloseAUp extends SimpleNode {
  public ASTcloseAUp(int id) {
    super(id);
  }

  public ASTcloseAUp(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfb10e20d08bc5596c1693beb60cf5c6 (do not edit this line) */
