/* Generated By:JJTree: Do not edit this line. ASTCbranchLink.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTCbranchLink extends SimpleNode {
  public ASTCbranchLink(int id) {
    super(id);
  }

  public ASTCbranchLink(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=29724e8c2212c90c841387ee50ceceab (do not edit this line) */
