/* Generated By:JJTree: Do not edit this line. ASThexadecimal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASThexadecimal extends SimpleNode {
  public ASThexadecimal(int id) {
    super(id);
  }

  public ASThexadecimal(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5fe15226bfbbfa67304bd964d23b528 (do not edit this line) */
