/* Generated By:JJTree: Do not edit this line. ASTldrSHPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrSHPreNeg extends SimpleNode {
  public ASTldrSHPreNeg(int id) {
    super(id);
  }

  public ASTldrSHPreNeg(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e4235b99eff56716c016eaf6c2203ae9 (do not edit this line) */
