/* Generated By:JJTree: Do not edit this line. ASTldrCSHPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCSHPreNeg extends SimpleNode {
  public ASTldrCSHPreNeg(int id) {
    super(id);
  }

  public ASTldrCSHPreNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a80a293898e4acabb09c3fa9619624a5 (do not edit this line) */
