/* Generated By:JJTree: Do not edit this line. ASTldrCSBPrePos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCSBPrePos extends SimpleNode {
  public ASTldrCSBPrePos(int id) {
    super(id);
  }

  public ASTldrCSBPrePos(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b006424f0e9fce52e6d4bfda5b6e78da (do not edit this line) */
