/* Generated By:JJTree: Do not edit this line. ASTldrSBPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrSBPreNeg extends SimpleNode {
  public ASTldrSBPreNeg(int id) {
    super(id);
  }

  public ASTldrSBPreNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49663b9871abe1cb633b5e77d01cc412 (do not edit this line) */
