/* Generated By:JJTree: Do not edit this line. ASTldrCSBPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCSBPreNeg extends SimpleNode {
  public ASTldrCSBPreNeg(int id) {
    super(id);
  }

  public ASTldrCSBPreNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98e19d0dd0ec70fe60ef817021819cb9 (do not edit this line) */
