/* Generated By:JJTree: Do not edit this line. ASTldrCBPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCBPreNeg extends SimpleNode {
  public ASTldrCBPreNeg(int id) {
    super(id);
  }

  public ASTldrCBPreNeg(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9bb6f394b9939daf638b54e4d02fd7d7 (do not edit this line) */
