/* Generated By:JJTree: Do not edit this line. ASTldmCEnum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldmCEnum extends SimpleNode {
  public ASTldmCEnum(int id) {
    super(id);
  }

  public ASTldmCEnum(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=39c3e81b4c02c279cc8cbff93675f595 (do not edit this line) */
