/* Generated By:JJTree: Do not edit this line. ASTlabBCBolck.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTlabBCBolck extends SimpleNode {
  public ASTlabBCBolck(int id) {
    super(id);
  }

  public ASTlabBCBolck(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bb63df4046882ad407aa87ed0e6c2490 (do not edit this line) */
