/* Generated By:JJTree: Do not edit this line. ASTldrCSBPostPos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCSBPostPos extends SimpleNode {
  public ASTldrCSBPostPos(int id) {
    super(id);
  }

  public ASTldrCSBPostPos(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3556d504b0f4d8870129add5583ab544 (do not edit this line) */
