/* Generated By:JJTree: Do not edit this line. ASTldrBPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrBPostNeg extends SimpleNode {
  public ASTldrBPostNeg(int id) {
    super(id);
  }

  public ASTldrBPostNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b76dc151c87da04993d4e3b1a7534dbb (do not edit this line) */
