/* Generated By:JJTree: Do not edit this line. ASTldrCSBPreNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCSBPreNeg extends SimpleNode {
  public ASTldrCSBPreNeg(int id) {
    super(id);
  }

  public ASTldrCSBPreNeg(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4c5924cd67ed8e32dd3872ff1f916fc1 (do not edit this line) */
