/* Generated By:JJTree: Do not edit this line. ASTldrCHPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTldrCHPostNeg extends SimpleNode {
  public ASTldrCHPostNeg(int id) {
    super(id);
  }

  public ASTldrCHPostNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=41c3162a91b5b7a220fa1361ccd50dc9 (do not edit this line) */
