/* Generated By:JJTree: Do not edit this line. ASTMldmCEnum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTMldmCEnum extends SimpleNode {
  public ASTMldmCEnum(int id) {
    super(id);
  }

  public ASTMldmCEnum(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=60beed65aeac0a9379a7efd7e2c7cfc9 (do not edit this line) */
