/* Generated By:JJTree: Do not edit this line. ASTMstmCEnum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTMstmCEnum extends SimpleNode {
  public ASTMstmCEnum(int id) {
    super(id);
  }

  public ASTMstmCEnum(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=479d39c2f2f5d6c025bcf250ce0b98fa (do not edit this line) */
