/* Generated By:JJTree: Do not edit this line. ASTMstmCSimple.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTMstmCSimple extends SimpleNode {
  public ASTMstmCSimple(int id) {
    super(id);
  }

  public ASTMstmCSimple(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=349a83043daf4ec0bd3f70da3d319536 (do not edit this line) */
