/* Generated By:JJTree: Do not edit this line. ASTstrSBPostPos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrSBPostPos extends SimpleNode {
  public ASTstrSBPostPos(int id) {
    super(id);
  }

  public ASTstrSBPostPos(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73141a92eb0ee92b9e3ec83ec64aa4ed (do not edit this line) */
