/* Generated By:JJTree: Do not edit this line. ASTstrHPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrHPostNeg extends SimpleNode {
  public ASTstrHPostNeg(int id) {
    super(id);
  }

  public ASTstrHPostNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1fcae2d2eb6fdf95ae5992899918f056 (do not edit this line) */
