/* Generated By:JJTree: Do not edit this line. ASTstrCPrePos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCPrePos extends SimpleNode {
  public ASTstrCPrePos(int id) {
    super(id);
  }

  public ASTstrCPrePos(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=315e6d5cfb4ccf41a7a5ae0c6ce7880a (do not edit this line) */
