/* Generated By:JJTree: Do not edit this line. ASTstrCHPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCHPostNeg extends SimpleNode {
  public ASTstrCHPostNeg(int id) {
    super(id);
  }

  public ASTstrCHPostNeg(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c20a7a229151fc2993c9b391a7550b3e (do not edit this line) */
