/* Generated By:JJTree: Do not edit this line. ASTstrCHPrePos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCHPrePos extends SimpleNode {
  public ASTstrCHPrePos(int id) {
    super(id);
  }

  public ASTstrCHPrePos(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=50811c29e3e4dbba4a0c7d15693c6c72 (do not edit this line) */
