/* Generated By:JJTree: Do not edit this line. ASTstrCSHPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCSHPostNeg extends SimpleNode {
  public ASTstrCSHPostNeg(int id) {
    super(id);
  }

  public ASTstrCSHPostNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=839f6586197433d1fcd047098e3a2d36 (do not edit this line) */
