/* Generated By:JJTree: Do not edit this line. ASTstrCSBPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCSBPostNeg extends SimpleNode {
  public ASTstrCSBPostNeg(int id) {
    super(id);
  }

  public ASTstrCSBPostNeg(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ad91989c82c9d629c6e72d88dfba0d8 (do not edit this line) */
