/* Generated By:JJTree: Do not edit this line. ASTshiftAndClose.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTshiftAndClose extends SimpleNode {
  public ASTshiftAndClose(int id) {
    super(id);
  }

  public ASTshiftAndClose(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7bb7d32f76320f391f12e975a4b19175 (do not edit this line) */
