/* Generated By:JJTree: Do not edit this line. ASTstmCEnum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstmCEnum extends SimpleNode {
  public ASTstmCEnum(int id) {
    super(id);
  }

  public ASTstmCEnum(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d5464819266e8759deeeb3b21ab500a5 (do not edit this line) */
