/* Generated By:JJTree: Do not edit this line. ASTstrSHPostPos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrSHPostPos extends SimpleNode {
  public ASTstrSHPostPos(int id) {
    super(id);
  }

  public ASTstrSHPostPos(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07250ff89a2d46f296f847c5feaed89d (do not edit this line) */
