/* Generated By:JJTree: Do not edit this line. ASTstrCSHPostPos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCSHPostPos extends SimpleNode {
  public ASTstrCSHPostPos(int id) {
    super(id);
  }

  public ASTstrCSHPostPos(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14ec4bcef18d7a0d8b0067895fc2942e (do not edit this line) */
