/* Generated By:JJTree: Do not edit this line. ASTstrSHSimple.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrSHSimple extends SimpleNode {
  public ASTstrSHSimple(int id) {
    super(id);
  }

  public ASTstrSHSimple(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a2b39c6f1c9c2c69b62159dade8e923d (do not edit this line) */
