/* Generated By:JJTree: Do not edit this line. ASTstrHPostNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=DataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrHPostNeg extends SimpleNode {
  public ASTstrHPostNeg(int id) {
    super(id);
  }

  public ASTstrHPostNeg(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e841acb43378d7cd6060303af485a4eb (do not edit this line) */
