/* Generated By:JJTree: Do not edit this line. ASTstrCSHPrePos.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=dataNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compAndInt;

public
class ASTstrCSHPrePos extends SimpleNode {
  public ASTstrCSHPrePos(int id) {
    super(id);
  }

  public ASTstrCSHPrePos(MyTest p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyTestVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8efb2227e1d937733ac81e2ac562b71b (do not edit this line) */
