/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
package compAndInt;

public interface MyParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTMOV = 2;
  public int JJTMOVS = 3;
  public int JJTMOVC = 4;
  public int JJTMOVCS = 5;
  public int JJTMVN = 6;
  public int JJTMVNS = 7;
  public int JJTMVNC = 8;
  public int JJTMVNCS = 9;
  public int JJTADD = 10;
  public int JJTADDS = 11;
  public int JJTADDC = 12;
  public int JJTADDCS = 13;
  public int JJTADC = 14;
  public int JJTADCS = 15;
  public int JJTADCC = 16;
  public int JJTADCCS = 17;
  public int JJTSUB = 18;
  public int JJTSUBS = 19;
  public int JJTSUBC = 20;
  public int JJTSUBCS = 21;
  public int JJTSBC = 22;
  public int JJTSBCS = 23;
  public int JJTSBCC = 24;
  public int JJTSBCCS = 25;
  public int JJTRSB = 26;
  public int JJTRSBS = 27;
  public int JJTRSBC = 28;
  public int JJTRSBCS = 29;
  public int JJTRSC = 30;
  public int JJTRSCS = 31;
  public int JJTRSCC = 32;
  public int JJTRSCCS = 33;
  public int JJTMLA = 34;
  public int JJTMLAS = 35;
  public int JJTMLAC = 36;
  public int JJTMLACS = 37;
  public int JJTMUL = 38;
  public int JJTMULS = 39;
  public int JJTMULC = 40;
  public int JJTMULCS = 41;
  public int JJTSMLAL = 42;
  public int JJTSMLALS = 43;
  public int JJTSMLALC = 44;
  public int JJTSMLALCS = 45;
  public int JJTSMULL = 46;
  public int JJTSMULLS = 47;
  public int JJTSMULLC = 48;
  public int JJTSMULLCS = 49;
  public int JJTUMLAL = 50;
  public int JJTUMLALS = 51;
  public int JJTUMLALC = 52;
  public int JJTUMLALCS = 53;
  public int JJTUMULL = 54;
  public int JJTUMULLS = 55;
  public int JJTUMULLC = 56;
  public int JJTUMULLCS = 57;
  public int JJTCMP = 58;
  public int JJTCMPC = 59;
  public int JJTCMN = 60;
  public int JJTCMNC = 61;
  public int JJTTEQ = 62;
  public int JJTTEQC = 63;
  public int JJTTST = 64;
  public int JJTTSTC = 65;
  public int JJTAND = 66;
  public int JJTANDS = 67;
  public int JJTANDC = 68;
  public int JJTANDCS = 69;
  public int JJTBIC = 70;
  public int JJTBICS = 71;
  public int JJTBICC = 72;
  public int JJTBICCS = 73;
  public int JJTEOR = 74;
  public int JJTEORS = 75;
  public int JJTEORC = 76;
  public int JJTEORCS = 77;
  public int JJTORR = 78;
  public int JJTORRS = 79;
  public int JJTORRC = 80;
  public int JJTORRCS = 81;
  public int JJTLDRPRENEG = 82;
  public int JJTLDRPREPOS = 83;
  public int JJTLDRPOSTNEG = 84;
  public int JJTLDRPOSTPOS = 85;
  public int JJTLDRSIMPLE = 86;
  public int JJTLDRBPRENEG = 87;
  public int JJTLDRBPREPOS = 88;
  public int JJTLDRBPOSTNEG = 89;
  public int JJTLDRBPOSTPOS = 90;
  public int JJTLDRBSIMPLE = 91;
  public int JJTLDRHPRENEG = 92;
  public int JJTLDRHPREPOS = 93;
  public int JJTLDRHPOSTNEG = 94;
  public int JJTLDRHPOSTPOS = 95;
  public int JJTLDRHSIMPLE = 96;
  public int JJTLDRSHPRENEG = 97;
  public int JJTLDRSHPREPOS = 98;
  public int JJTLDRSHPOSTNEG = 99;
  public int JJTLDRSHPOSTPOS = 100;
  public int JJTLDRSHSIMPLE = 101;
  public int JJTLDRSBPRENEG = 102;
  public int JJTLDRSBPREPOS = 103;
  public int JJTLDRSBPOSTNEG = 104;
  public int JJTLDRSBPOSTPOS = 105;
  public int JJTLDRSBSIMPLE = 106;
  public int JJTLDRCPRENEG = 107;
  public int JJTLDRCPREPOS = 108;
  public int JJTLDRCPOSTNEG = 109;
  public int JJTLDRCPOSTPOS = 110;
  public int JJTLDRCSIMPLE = 111;
  public int JJTLDRCBPRENEG = 112;
  public int JJTLDRCBPREPOS = 113;
  public int JJTLDRCBPOSTNEG = 114;
  public int JJTLDRCBPOSTPOS = 115;
  public int JJTLDRCBSIMPLE = 116;
  public int JJTLDRCHPRENEG = 117;
  public int JJTLDRCHPREPOS = 118;
  public int JJTLDRCHPOSTNEG = 119;
  public int JJTLDRCHPOSTPOS = 120;
  public int JJTLDRCHSIMPLE = 121;
  public int JJTLDRCSHPRENEG = 122;
  public int JJTLDRCSHPREPOS = 123;
  public int JJTLDRCSHPOSTNEG = 124;
  public int JJTLDRCSHPOSTPOS = 125;
  public int JJTLDRCSHSIMPLE = 126;
  public int JJTLDRCSBPRENEG = 127;
  public int JJTLDRCSBPREPOS = 128;
  public int JJTLDRCSBPOSTNEG = 129;
  public int JJTLDRCSBPOSTPOS = 130;
  public int JJTLDRCSBSIMPLE = 131;
  public int JJTSTRPRENEG = 132;
  public int JJTSTRPREPOS = 133;
  public int JJTSTRPOSTNEG = 134;
  public int JJTSTRPOSTPOS = 135;
  public int JJTSTRSIMPLE = 136;
  public int JJTSTRBPRENEG = 137;
  public int JJTSTRBPREPOS = 138;
  public int JJTSTRBPOSTNEG = 139;
  public int JJTSTRBPOSTPOS = 140;
  public int JJTSTRBSIMPLE = 141;
  public int JJTSTRHPRENEG = 142;
  public int JJTSTRHPREPOS = 143;
  public int JJTSTRHPOSTNEG = 144;
  public int JJTSTRHPOSTPOS = 145;
  public int JJTSTRHSIMPLE = 146;
  public int JJTSTRCPRENEG = 147;
  public int JJTSTRCPREPOS = 148;
  public int JJTSTRCPOSTNEG = 149;
  public int JJTSTRCPOSTPOS = 150;
  public int JJTSTRCSIMPLE = 151;
  public int JJTSTRCBPRENEG = 152;
  public int JJTSTRCBPREPOS = 153;
  public int JJTSTRCBPOSTNEG = 154;
  public int JJTSTRCBPOSTPOS = 155;
  public int JJTSTRCBSIMPLE = 156;
  public int JJTSTRCHPRENEG = 157;
  public int JJTSTRCHPREPOS = 158;
  public int JJTSTRCHPOSTNEG = 159;
  public int JJTSTRCHPOSTPOS = 160;
  public int JJTSTRCHSIMPLE = 161;
  public int JJTLDMSIMPLE = 162;
  public int JJTLDMLIST = 163;
  public int JJTMLDMSIMPLE = 164;
  public int JJTMLDMLIST = 165;
  public int JJTLDMCSIMPLE = 166;
  public int JJTLDMCLIST = 167;
  public int JJTMLDMCSIMPLE = 168;
  public int JJTMLDMCLIST = 169;
  public int JJTMLDMENUM = 170;
  public int JJTLDMENUM = 171;
  public int JJTLDMCENUM = 172;
  public int JJTMLDMCENUM = 173;
  public int JJTSTMSIMPLE = 174;
  public int JJTSTMLIST = 175;
  public int JJTMSTMSIMPLE = 176;
  public int JJTMSTMLIST = 177;
  public int JJTSTMCSIMPLE = 178;
  public int JJTSTMCLIST = 179;
  public int JJTMSTMCSIMPLE = 180;
  public int JJTMSTMCLIST = 181;
  public int JJTMSTMENUM = 182;
  public int JJTSTMENUM = 183;
  public int JJTSTMCENUM = 184;
  public int JJTMSTMCENUM = 185;
  public int JJTSWP = 186;
  public int JJTSWPB = 187;
  public int JJTSWPC = 188;
  public int JJTSWPCB = 189;
  public int JJTSWI = 190;
  public int JJTCSWI = 191;
  public int JJTCBRANCH = 192;
  public int JJTBRANCH = 193;
  public int JJTCBRANCHLINK = 194;
  public int JJTBRANCHLINK = 195;
  public int JJTCLOSEAUP = 196;
  public int JJTCLOSE = 197;
  public int JJTSHIFTLS = 198;
  public int JJTSHIFTF = 199;
  public int JJTAMODE = 200;
  public int JJTCOND = 201;
  public int JJTLSL = 202;
  public int JJTLSR = 203;
  public int JJTASR = 204;
  public int JJTROR = 205;
  public int JJTSHIFT = 206;
  public int JJTREGISTER = 207;
  public int JJTNUMBER = 208;
  public int JJTHEXA = 209;
  public int JJTHEXADECIMAL = 210;
  public int JJTNUM = 211;
  public int JJTLABEL = 212;


  public String[] jjtNodeName = {
    "prog",
    "void",
    "mov",
    "movS",
    "movC",
    "movCS",
    "mvn",
    "mvnS",
    "mvnC",
    "mvnCS",
    "add",
    "addS",
    "addC",
    "addCS",
    "adc",
    "adcS",
    "adcC",
    "adcCS",
    "sub",
    "subS",
    "subC",
    "subCS",
    "sbc",
    "sbcS",
    "sbcC",
    "sbcCS",
    "rsb",
    "rsbS",
    "rsbC",
    "rsbCS",
    "rsc",
    "rscS",
    "rscC",
    "rscCS",
    "mla",
    "mlaS",
    "mlaC",
    "mlaCS",
    "mul",
    "mulS",
    "mulC",
    "mulCS",
    "smlal",
    "smlalS",
    "smlalC",
    "smlalCS",
    "smull",
    "smullS",
    "smullC",
    "smullCS",
    "umlal",
    "umlalS",
    "umlalC",
    "umlalCS",
    "umull",
    "umullS",
    "umullC",
    "umullCS",
    "cmp",
    "cmpC",
    "cmn",
    "cmnC",
    "teq",
    "teqC",
    "tst",
    "tstC",
    "and",
    "andS",
    "andC",
    "andCS",
    "bic",
    "bicS",
    "bicC",
    "bicCS",
    "eor",
    "eorS",
    "eorC",
    "eorCS",
    "orr",
    "orrS",
    "orrC",
    "orrCS",
    "ldrPreNeg",
    "ldrPrePos",
    "ldrPostNeg",
    "ldrPostPos",
    "ldrSimple",
    "ldrBPreNeg",
    "ldrBPrePos",
    "ldrBPostNeg",
    "ldrBPostPos",
    "ldrBSimple",
    "ldrHPreNeg",
    "ldrHPrePos",
    "ldrHPostNeg",
    "ldrHPostPos",
    "ldrHSimple",
    "ldrSHPreNeg",
    "ldrSHPrePos",
    "ldrSHPostNeg",
    "ldrSHPostPos",
    "ldrSHSimple",
    "ldrSBPreNeg",
    "ldrSBPrePos",
    "ldrSBPostNeg",
    "ldrSBPostPos",
    "ldrSBSimple",
    "ldrCPreNeg",
    "ldrCPrePos",
    "ldrCPostNeg",
    "ldrCPostPos",
    "ldrCSimple",
    "ldrCBPreNeg",
    "ldrCBPrePos",
    "ldrCBPostNeg",
    "ldrCBPostPos",
    "ldrCBSimple",
    "ldrCHPreNeg",
    "ldrCHPrePos",
    "ldrCHPostNeg",
    "ldrCHPostPos",
    "ldrCHSimple",
    "ldrCSHPreNeg",
    "ldrCSHPrePos",
    "ldrCSHPostNeg",
    "ldrCSHPostPos",
    "ldrCSHSimple",
    "ldrCSBPreNeg",
    "ldrCSBPrePos",
    "ldrCSBPostNeg",
    "ldrCSBPostPos",
    "ldrCSBSimple",
    "strPreNeg",
    "strPrePos",
    "strPostNeg",
    "strPostPos",
    "strSimple",
    "strBPreNeg",
    "strBPrePos",
    "strBPostNeg",
    "strBPostPos",
    "strBSimple",
    "strHPreNeg",
    "strHPrePos",
    "strHPostNeg",
    "strHPostPos",
    "strHSimple",
    "strCPreNeg",
    "strCPrePos",
    "strCPostNeg",
    "strCPostPos",
    "strCSimple",
    "strCBPreNeg",
    "strCBPrePos",
    "strCBPostNeg",
    "strCBPostPos",
    "strCBSimple",
    "strCHPreNeg",
    "strCHPrePos",
    "strCHPostNeg",
    "strCHPostPos",
    "strCHSimple",
    "ldmSimple",
    "ldmList",
    "MldmSimple",
    "MldmList",
    "ldmCSimple",
    "ldmCList",
    "MldmCSimple",
    "MldmCList",
    "MldmEnum",
    "ldmEnum",
    "ldmCEnum",
    "MldmCEnum",
    "stmSimple",
    "stmList",
    "MstmSimple",
    "MstmList",
    "stmCSimple",
    "stmCList",
    "MstmCSimple",
    "MstmCList",
    "MstmEnum",
    "stmEnum",
    "stmCEnum",
    "MstmCEnum",
    "swp",
    "swpb",
    "swpC",
    "swpCB",
    "swi",
    "Cswi",
    "Cbranch",
    "branch",
    "CbranchLink",
    "branchLink",
    "closeAUp",
    "close",
    "shiftLS",
    "shiftF",
    "amode",
    "cond",
    "lsl",
    "lsr",
    "asr",
    "ror",
    "shift",
    "register",
    "number",
    "hexa",
    "hexadecimal",
    "num",
    "label",
  };
}
/* JavaCC - OriginalChecksum=7a618bee9bd80f12c4af688ec815fe8c (do not edit this line) */
