/* Generated By:JJTree&JavaCC: Do not edit this line. MyParserConstants.java */
package compAndInt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int B = 5;
  /** RegularExpression Id. */
  int H = 6;
  /** RegularExpression Id. */
  int L = 7;
  /** RegularExpression Id. */
  int AMODE = 8;
  /** RegularExpression Id. */
  int COND = 9;
  /** RegularExpression Id. */
  int SCND = 10;
  /** RegularExpression Id. */
  int LSL = 11;
  /** RegularExpression Id. */
  int LSR = 12;
  /** RegularExpression Id. */
  int ASR = 13;
  /** RegularExpression Id. */
  int ROR = 14;
  /** RegularExpression Id. */
  int SHIFT = 15;
  /** RegularExpression Id. */
  int MOV = 16;
  /** RegularExpression Id. */
  int MVN = 17;
  /** RegularExpression Id. */
  int ADD = 18;
  /** RegularExpression Id. */
  int ADC = 19;
  /** RegularExpression Id. */
  int SUB = 20;
  /** RegularExpression Id. */
  int SBC = 21;
  /** RegularExpression Id. */
  int RSB = 22;
  /** RegularExpression Id. */
  int RSC = 23;
  /** RegularExpression Id. */
  int MLA = 24;
  /** RegularExpression Id. */
  int MUL = 25;
  /** RegularExpression Id. */
  int SMLAL = 26;
  /** RegularExpression Id. */
  int SMULL = 27;
  /** RegularExpression Id. */
  int UMLAL = 28;
  /** RegularExpression Id. */
  int UMULL = 29;
  /** RegularExpression Id. */
  int CMP = 30;
  /** RegularExpression Id. */
  int CMN = 31;
  /** RegularExpression Id. */
  int TEQ = 32;
  /** RegularExpression Id. */
  int TST = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int BIC = 35;
  /** RegularExpression Id. */
  int EOR = 36;
  /** RegularExpression Id. */
  int ORR = 37;
  /** RegularExpression Id. */
  int LDR = 38;
  /** RegularExpression Id. */
  int STR = 39;
  /** RegularExpression Id. */
  int LDM = 40;
  /** RegularExpression Id. */
  int STM = 41;
  /** RegularExpression Id. */
  int SWP = 42;
  /** RegularExpression Id. */
  int SWI = 43;
  /** RegularExpression Id. */
  int NUMBER = 44;
  /** RegularExpression Id. */
  int REGISTER = 45;
  /** RegularExpression Id. */
  int HEXA = 46;
  /** RegularExpression Id. */
  int HEXADECIMAL = 47;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int LABEL = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"b\"",
    "\"h\"",
    "\"l\"",
    "<AMODE>",
    "<COND>",
    "\"s\"",
    "\"lsl\"",
    "\"lsr\"",
    "\"asr\"",
    "\"ror\"",
    "<SHIFT>",
    "\"mov\"",
    "\"mvn\"",
    "\"add\"",
    "\"adc\"",
    "\"sub\"",
    "\"sbc\"",
    "\"rsb\"",
    "\"rsc\"",
    "\"mla\"",
    "\"mul\"",
    "\"smlal\"",
    "\"smull\"",
    "\"umlal\"",
    "\"umull\"",
    "\"cmp\"",
    "\"cmn\"",
    "\"teq\"",
    "\"tst\"",
    "\"and\"",
    "\"bic\"",
    "\"eor\"",
    "\"orr\"",
    "\"ldr\"",
    "\"str\"",
    "\"ldm\"",
    "\"stm\"",
    "\"swp\"",
    "\"swi\"",
    "<NUMBER>",
    "<REGISTER>",
    "<HEXA>",
    "<HEXADECIMAL>",
    "<NUM>",
    "<LABEL>",
    "\",\"",
    "\"[\"",
    "\"-\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"^\"",
    "\"!\"",
  };

}
