/* Generated By:JavaCC: Do not edit this line. MyTestTreeConstants.java Version 5.0 */
package compAndInt;

public interface MyTestTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTDECLS = 3;
  public int JJTDECLC = 4;
  public int JJTDECLCS = 5;
  public int JJTDECLN = 6;
  public int JJTDECLNS = 7;
  public int JJTDECLNC = 8;
  public int JJTDECLNCS = 9;
  public int JJTADD = 10;
  public int JJTADDS = 11;
  public int JJTADDC = 12;
  public int JJTADDCS = 13;
  public int JJTADC = 14;
  public int JJTADCS = 15;
  public int JJTADCC = 16;
  public int JJTADCCS = 17;
  public int JJTSUB = 18;
  public int JJTSUBS = 19;
  public int JJTSUBC = 20;
  public int JJTSUBCS = 21;
  public int JJTSBC = 22;
  public int JJTSBCS = 23;
  public int JJTSBCC = 24;
  public int JJTSBCCS = 25;
  public int JJTRSB = 26;
  public int JJTRSBS = 27;
  public int JJTRSBC = 28;
  public int JJTRSBCS = 29;
  public int JJTRSC = 30;
  public int JJTRSCS = 31;
  public int JJTRSCC = 32;
  public int JJTRSCCS = 33;
  public int JJTCMP = 34;
  public int JJTCMPC = 35;
  public int JJTCMN = 36;
  public int JJTCMNC = 37;
  public int JJTTEQ = 38;
  public int JJTTEQC = 39;
  public int JJTTST = 40;
  public int JJTTSTC = 41;
  public int JJTAND = 42;
  public int JJTANDS = 43;
  public int JJTANDC = 44;
  public int JJTANDCS = 45;
  public int JJTBIC = 46;
  public int JJTBICS = 47;
  public int JJTBICC = 48;
  public int JJTBICCS = 49;
  public int JJTEOR = 50;
  public int JJTEORS = 51;
  public int JJTEORC = 52;
  public int JJTEORCS = 53;
  public int JJTORR = 54;
  public int JJTORRS = 55;
  public int JJTORRC = 56;
  public int JJTORRCS = 57;
  public int JJTLDRPRENEG = 58;
  public int JJTLDRPREPOS = 59;
  public int JJTLDRPOSTNEG = 60;
  public int JJTLDRPOSTPOS = 61;
  public int JJTLDRSIMPLE = 62;
  public int JJTLDRBPRENEG = 63;
  public int JJTLDRBPREPOS = 64;
  public int JJTLDRBPOSTNEG = 65;
  public int JJTLDRBPOSTPOS = 66;
  public int JJTLDRBSIMPLE = 67;
  public int JJTLDRHPRENEG = 68;
  public int JJTLDRHPREPOS = 69;
  public int JJTLDRHPOSTNEG = 70;
  public int JJTLDRHPOSTPOS = 71;
  public int JJTLDRHSIMPLE = 72;
  public int JJTLDRSHPRENEG = 73;
  public int JJTLDRSHPREPOS = 74;
  public int JJTLDRSHPOSTNEG = 75;
  public int JJTLDRSHPOSTPOS = 76;
  public int JJTLDRSHSIMPLE = 77;
  public int JJTLDRSBPRENEG = 78;
  public int JJTLDRSBPREPOS = 79;
  public int JJTLDRSBPOSTNEG = 80;
  public int JJTLDRSBPOSTPOS = 81;
  public int JJTLDRSBSIMPLE = 82;
  public int JJTLDRCPRENEG = 83;
  public int JJTLDRCPREPOS = 84;
  public int JJTLDRCPOSTNEG = 85;
  public int JJTLDRCPOSTPOS = 86;
  public int JJTLDRCSIMPLE = 87;
  public int JJTLDRCBPRENEG = 88;
  public int JJTLDRCBPREPOS = 89;
  public int JJTLDRCBPOSTNEG = 90;
  public int JJTLDRCBPOSTPOS = 91;
  public int JJTLDRCBSIMPLE = 92;
  public int JJTLDRCHPRENEG = 93;
  public int JJTLDRCHPREPOS = 94;
  public int JJTLDRCHPOSTNEG = 95;
  public int JJTLDRCHPOSTPOS = 96;
  public int JJTLDRCHSIMPLE = 97;
  public int JJTLDRCSHPRENEG = 98;
  public int JJTLDRCSHPREPOS = 99;
  public int JJTLDRCSHPOSTNEG = 100;
  public int JJTLDRCSHPOSTPOS = 101;
  public int JJTLDRCSHSIMPLE = 102;
  public int JJTLDRCSBPRENEG = 103;
  public int JJTLDRCSBPREPOS = 104;
  public int JJTLDRCSBPOSTNEG = 105;
  public int JJTLDRCSBPOSTPOS = 106;
  public int JJTLDRCSBSIMPLE = 107;
  public int JJTSTRPRENEG = 108;
  public int JJTSTRPREPOS = 109;
  public int JJTSTRPOSTNEG = 110;
  public int JJTSTRPOSTPOS = 111;
  public int JJTSTRSIMPLE = 112;
  public int JJTSTRBPRENEG = 113;
  public int JJTSTRBPREPOS = 114;
  public int JJTSTRBPOSTNEG = 115;
  public int JJTSTRBPOSTPOS = 116;
  public int JJTSTRBSIMPLE = 117;
  public int JJTSTRHPRENEG = 118;
  public int JJTSTRHPREPOS = 119;
  public int JJTSTRHPOSTNEG = 120;
  public int JJTSTRHPOSTPOS = 121;
  public int JJTSTRHSIMPLE = 122;
  public int JJTSTRSHPRENEG = 123;
  public int JJTSTRSHPREPOS = 124;
  public int JJTSTRSHPOSTNEG = 125;
  public int JJTSTRSHPOSTPOS = 126;
  public int JJTSTRSHSIMPLE = 127;
  public int JJTSTRSBPRENEG = 128;
  public int JJTSTRSBPREPOS = 129;
  public int JJTSTRSBPOSTNEG = 130;
  public int JJTSTRSBPOSTPOS = 131;
  public int JJTSTRSBSIMPLE = 132;
  public int JJTSTRCPRENEG = 133;
  public int JJTSTRCPREPOS = 134;
  public int JJTSTRCPOSTNEG = 135;
  public int JJTSTRCPOSTPOS = 136;
  public int JJTSTRCSIMPLE = 137;
  public int JJTSTRCBPRENEG = 138;
  public int JJTSTRCBPREPOS = 139;
  public int JJTSTRCBPOSTNEG = 140;
  public int JJTSTRCBPOSTPOS = 141;
  public int JJTSTRCBSIMPLE = 142;
  public int JJTSTRCHPRENEG = 143;
  public int JJTSTRCHPREPOS = 144;
  public int JJTSTRCHPOSTNEG = 145;
  public int JJTSTRCHPOSTPOS = 146;
  public int JJTSTRCHSIMPLE = 147;
  public int JJTSTRCSHPRENEG = 148;
  public int JJTSTRCSHPREPOS = 149;
  public int JJTSTRCSHPOSTNEG = 150;
  public int JJTSTRCSHPOSTPOS = 151;
  public int JJTSTRCSHSIMPLE = 152;
  public int JJTSTRCSBPRENEG = 153;
  public int JJTSTRCSBPREPOS = 154;
  public int JJTSTRCSBPOSTNEG = 155;
  public int JJTSTRCSBPOSTPOS = 156;
  public int JJTSTRCSBSIMPLE = 157;
  public int JJTLDMSIMPLE = 158;
  public int JJTLDMENUM = 159;
  public int JJTLDMLIST = 160;
  public int JJTMLDMSIMPLE = 161;
  public int JJTMLDMENUM = 162;
  public int JJTMLDMLIST = 163;
  public int JJTLDMCSIMPLE = 164;
  public int JJTLDMCENUM = 165;
  public int JJTLDMCLIST = 166;
  public int JJTMLDMCSIMPLE = 167;
  public int JJTMLDMCENUM = 168;
  public int JJTMLDMCLIST = 169;
  public int JJTSTMSIMPLE = 170;
  public int JJTSTMENUM = 171;
  public int JJTSTMLIST = 172;
  public int JJTMSTMSIMPLE = 173;
  public int JJTMSTMENUM = 174;
  public int JJTMSTMLIST = 175;
  public int JJTSTMCSIMPLE = 176;
  public int JJTSTMCENUM = 177;
  public int JJTSTMCLIST = 178;
  public int JJTMSTMCSIMPLE = 179;
  public int JJTMSTMCENUM = 180;
  public int JJTMSTMCLIST = 181;
  public int JJTCLOSEAUP = 182;
  public int JJTCLOSE = 183;
  public int JJTSHIFTLS = 184;
  public int JJTSHIFTF = 185;
  public int JJTAMODE = 186;
  public int JJTCOND = 187;
  public int JJTLSL = 188;
  public int JJTLSR = 189;
  public int JJTASR = 190;
  public int JJTROR = 191;
  public int JJTSHIFT = 192;
  public int JJTREGISTER = 193;
  public int JJTNUMBER = 194;
  public int JJTHEXA = 195;
  public int JJTNUM = 196;


  public String[] jjtNodeName = {
    "prog",
    "void",
    "decl",
    "declS",
    "declC",
    "declCS",
    "decln",
    "declnS",
    "declnC",
    "declnCS",
    "add",
    "addS",
    "addC",
    "addCS",
    "adc",
    "adcS",
    "adcC",
    "adcCS",
    "sub",
    "subS",
    "subC",
    "subCS",
    "sbc",
    "sbcS",
    "sbcC",
    "sbcCS",
    "rsb",
    "rsbS",
    "rsbC",
    "rsbCS",
    "rsc",
    "rscS",
    "rscC",
    "rscCS",
    "cmp",
    "cmpC",
    "cmn",
    "cmnC",
    "teq",
    "teqC",
    "tst",
    "tstC",
    "and",
    "andS",
    "andC",
    "andCS",
    "bic",
    "bicS",
    "bicC",
    "bicCS",
    "eor",
    "eorS",
    "eorC",
    "eorCS",
    "orr",
    "orrS",
    "orrC",
    "orrCS",
    "ldrPreNeg",
    "ldrPrePos",
    "ldrPostNeg",
    "ldrPostPos",
    "ldrSimple",
    "ldrBPreNeg",
    "ldrBPrePos",
    "ldrBPostNeg",
    "ldrBPostPos",
    "ldrBSimple",
    "ldrHPreNeg",
    "ldrHPrePos",
    "ldrHPostNeg",
    "ldrHPostPos",
    "ldrHSimple",
    "ldrSHPreNeg",
    "ldrSHPrePos",
    "ldrSHPostNeg",
    "ldrSHPostPos",
    "ldrSHSimple",
    "ldrSBPreNeg",
    "ldrSBPrePos",
    "ldrSBPostNeg",
    "ldrSBPostPos",
    "ldrSBSimple",
    "ldrCPreNeg",
    "ldrCPrePos",
    "ldrCPostNeg",
    "ldrCPostPos",
    "ldrCSimple",
    "ldrCBPreNeg",
    "ldrCBPrePos",
    "ldrCBPostNeg",
    "ldrCBPostPos",
    "ldrCBSimple",
    "ldrCHPreNeg",
    "ldrCHPrePos",
    "ldrCHPostNeg",
    "ldrCHPostPos",
    "ldrCHSimple",
    "ldrCSHPreNeg",
    "ldrCSHPrePos",
    "ldrCSHPostNeg",
    "ldrCSHPostPos",
    "ldrCSHSimple",
    "ldrCSBPreNeg",
    "ldrCSBPrePos",
    "ldrCSBPostNeg",
    "ldrCSBPostPos",
    "ldrCSBSimple",
    "strPreNeg",
    "strPrePos",
    "strPostNeg",
    "strPostPos",
    "strSimple",
    "strBPreNeg",
    "strBPrePos",
    "strBPostNeg",
    "strBPostPos",
    "strBSimple",
    "strHPreNeg",
    "strHPrePos",
    "strHPostNeg",
    "strHPostPos",
    "strHSimple",
    "strSHPreNeg",
    "strSHPrePos",
    "strSHPostNeg",
    "strSHPostPos",
    "strSHSimple",
    "strSBPreNeg",
    "strSBPrePos",
    "strSBPostNeg",
    "strSBPostPos",
    "strSBSimple",
    "strCPreNeg",
    "strCPrePos",
    "strCPostNeg",
    "strCPostPos",
    "strCSimple",
    "strCBPreNeg",
    "strCBPrePos",
    "strCBPostNeg",
    "strCBPostPos",
    "strCBSimple",
    "strCHPreNeg",
    "strCHPrePos",
    "strCHPostNeg",
    "strCHPostPos",
    "strCHSimple",
    "strCSHPreNeg",
    "strCSHPrePos",
    "strCSHPostNeg",
    "strCSHPostPos",
    "strCSHSimple",
    "strCSBPreNeg",
    "strCSBPrePos",
    "strCSBPostNeg",
    "strCSBPostPos",
    "strCSBSimple",
    "ldmSimple",
    "ldmEnum",
    "ldmList",
    "MldmSimple",
    "MldmEnum",
    "MldmList",
    "ldmCSimple",
    "ldmCEnum",
    "ldmCList",
    "MldmCSimple",
    "MldmCEnum",
    "MldmCList",
    "stmSimple",
    "stmEnum",
    "stmList",
    "MstmSimple",
    "MstmEnum",
    "MstmList",
    "stmCSimple",
    "stmCEnum",
    "stmCList",
    "MstmCSimple",
    "MstmCEnum",
    "MstmCList",
    "closeAUp",
    "close",
    "shiftLS",
    "shiftF",
    "amode",
    "cond",
    "lsl",
    "lsr",
    "asr",
    "ror",
    "shift",
    "register",
    "number",
    "hexa",
    "num",
  };
}
/* JavaCC - OriginalChecksum=0316c97499dae9f1be0d5fea04bdb9f0 (do not edit this line) */
