/* Generated By:JJTree&JavaCC: Do not edit this line. MyTestConstants.java */
package compAndInt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyTestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COND = 5;
  /** RegularExpression Id. */
  int SCND = 6;
  /** RegularExpression Id. */
  int LSL = 7;
  /** RegularExpression Id. */
  int LSR = 8;
  /** RegularExpression Id. */
  int SHIFT = 9;
  /** RegularExpression Id. */
  int MOV = 10;
  /** RegularExpression Id. */
  int MVN = 11;
  /** RegularExpression Id. */
  int ADD = 12;
  /** RegularExpression Id. */
  int ADC = 13;
  /** RegularExpression Id. */
  int SUB = 14;
  /** RegularExpression Id. */
  int SBC = 15;
  /** RegularExpression Id. */
  int RSB = 16;
  /** RegularExpression Id. */
  int RSC = 17;
  /** RegularExpression Id. */
  int CMP = 18;
  /** RegularExpression Id. */
  int CMN = 19;
  /** RegularExpression Id. */
  int TEQ = 20;
  /** RegularExpression Id. */
  int TST = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int BIC = 23;
  /** RegularExpression Id. */
  int EOR = 24;
  /** RegularExpression Id. */
  int ORR = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int REGISTER = 27;
  /** RegularExpression Id. */
  int HEXA = 28;
  /** RegularExpression Id. */
  int NUM = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COND>",
    "\"s\"",
    "\"lsl\"",
    "\"lsr\"",
    "<SHIFT>",
    "\"mov\"",
    "\"mvn\"",
    "\"add\"",
    "\"adc\"",
    "\"sub\"",
    "\"sbc\"",
    "\"rsb\"",
    "\"rsc\"",
    "\"cmp\"",
    "\"cmn\"",
    "\"teq\"",
    "\"tst\"",
    "\"and\"",
    "\"bic\"",
    "\"eor\"",
    "\"orr\"",
    "<NUMBER>",
    "<REGISTER>",
    "<HEXA>",
    "<NUM>",
    "\",\"",
  };

}
