/* Generated By:JJTree&JavaCC: Do not edit this line. MyTestConstants.java */
package compAndInt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyTestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int B = 5;
  /** RegularExpression Id. */
  int H = 6;
  /** RegularExpression Id. */
  int AMODE = 7;
  /** RegularExpression Id. */
  int COND = 8;
  /** RegularExpression Id. */
  int SCND = 9;
  /** RegularExpression Id. */
  int LSL = 10;
  /** RegularExpression Id. */
  int LSR = 11;
  /** RegularExpression Id. */
  int ASR = 12;
  /** RegularExpression Id. */
  int ROR = 13;
  /** RegularExpression Id. */
  int SHIFT = 14;
  /** RegularExpression Id. */
  int MOV = 15;
  /** RegularExpression Id. */
  int MVN = 16;
  /** RegularExpression Id. */
  int ADD = 17;
  /** RegularExpression Id. */
  int ADC = 18;
  /** RegularExpression Id. */
  int SUB = 19;
  /** RegularExpression Id. */
  int SBC = 20;
  /** RegularExpression Id. */
  int RSB = 21;
  /** RegularExpression Id. */
  int RSC = 22;
  /** RegularExpression Id. */
  int MLA = 23;
  /** RegularExpression Id. */
  int MUL = 24;
  /** RegularExpression Id. */
  int SMLAL = 25;
  /** RegularExpression Id. */
  int SMULL = 26;
  /** RegularExpression Id. */
  int CMP = 27;
  /** RegularExpression Id. */
  int CMN = 28;
  /** RegularExpression Id. */
  int TEQ = 29;
  /** RegularExpression Id. */
  int TST = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int BIC = 32;
  /** RegularExpression Id. */
  int EOR = 33;
  /** RegularExpression Id. */
  int ORR = 34;
  /** RegularExpression Id. */
  int LDR = 35;
  /** RegularExpression Id. */
  int STR = 36;
  /** RegularExpression Id. */
  int LDM = 37;
  /** RegularExpression Id. */
  int STM = 38;
  /** RegularExpression Id. */
  int NUMBER = 39;
  /** RegularExpression Id. */
  int REGISTER = 40;
  /** RegularExpression Id. */
  int HEXA = 41;
  /** RegularExpression Id. */
  int NUM = 42;
  /** RegularExpression Id. */
  int LABEL_B = 43;
  /** RegularExpression Id. */
  int B_LABEL = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"b\"",
    "\"h\"",
    "<AMODE>",
    "<COND>",
    "\"s\"",
    "\"lsl\"",
    "\"lsr\"",
    "\"asr\"",
    "\"ror\"",
    "<SHIFT>",
    "\"mov\"",
    "\"mvn\"",
    "\"add\"",
    "\"adc\"",
    "\"sub\"",
    "\"sbc\"",
    "\"rsb\"",
    "\"rsc\"",
    "\"mla\"",
    "\"mul\"",
    "\"smlal\"",
    "\"smull\"",
    "\"cmp\"",
    "\"cmn\"",
    "\"teq\"",
    "\"tst\"",
    "\"and\"",
    "\"bic\"",
    "\"eor\"",
    "\"orr\"",
    "\"ldr\"",
    "\"str\"",
    "\"ldm\"",
    "\"stm\"",
    "<NUMBER>",
    "<REGISTER>",
    "<HEXA>",
    "<NUM>",
    "<LABEL_B>",
    "<B_LABEL>",
    "\",\"",
    "\"[\"",
    "\"-\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"^\"",
    "\"!\"",
  };

}
