/* Generated By:JJTree&JavaCC: Do not edit this line. MyTestConstants.java */
package compAndInt;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyTestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int B = 5;
  /** RegularExpression Id. */
  int H = 6;
  /** RegularExpression Id. */
  int COND = 7;
  /** RegularExpression Id. */
  int SCND = 8;
  /** RegularExpression Id. */
  int LSL = 9;
  /** RegularExpression Id. */
  int LSR = 10;
  /** RegularExpression Id. */
  int ASR = 11;
  /** RegularExpression Id. */
  int ROR = 12;
  /** RegularExpression Id. */
  int SHIFT = 13;
  /** RegularExpression Id. */
  int MOV = 14;
  /** RegularExpression Id. */
  int MVN = 15;
  /** RegularExpression Id. */
  int ADD = 16;
  /** RegularExpression Id. */
  int ADC = 17;
  /** RegularExpression Id. */
  int SUB = 18;
  /** RegularExpression Id. */
  int SBC = 19;
  /** RegularExpression Id. */
  int RSB = 20;
  /** RegularExpression Id. */
  int RSC = 21;
  /** RegularExpression Id. */
  int CMP = 22;
  /** RegularExpression Id. */
  int CMN = 23;
  /** RegularExpression Id. */
  int TEQ = 24;
  /** RegularExpression Id. */
  int TST = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int BIC = 27;
  /** RegularExpression Id. */
  int EOR = 28;
  /** RegularExpression Id. */
  int ORR = 29;
  /** RegularExpression Id. */
  int LDR = 30;
  /** RegularExpression Id. */
  int STR = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int REGISTER = 33;
  /** RegularExpression Id. */
  int HEXA = 34;
  /** RegularExpression Id. */
  int NUM = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"b\"",
    "\"h\"",
    "<COND>",
    "\"s\"",
    "\"lsl\"",
    "\"lsr\"",
    "\"asr\"",
    "\"ror\"",
    "<SHIFT>",
    "\"mov\"",
    "\"mvn\"",
    "\"add\"",
    "\"adc\"",
    "\"sub\"",
    "\"sbc\"",
    "\"rsb\"",
    "\"rsc\"",
    "\"cmp\"",
    "\"cmn\"",
    "\"teq\"",
    "\"tst\"",
    "\"and\"",
    "\"bic\"",
    "\"eor\"",
    "\"orr\"",
    "\"ldr\"",
    "\"str\"",
    "<NUMBER>",
    "<REGISTER>",
    "<HEXA>",
    "<NUM>",
    "\",\"",
    "\"[\"",
    "\"-\"",
    "\"]\"",
    "\"!\"",
  };

}
