/* Generated By:JavaCC: Do not edit this line. MyTestTreeConstants.java Version 5.0 */
package compAndInt;

public interface MyTestTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTDECLS = 3;
  public int JJTDECLC = 4;
  public int JJTDECLCS = 5;
  public int JJTDECLN = 6;
  public int JJTDECLNS = 7;
  public int JJTDECLNC = 8;
  public int JJTDECLNCS = 9;
  public int JJTADD = 10;
  public int JJTADDS = 11;
  public int JJTADDC = 12;
  public int JJTADDCS = 13;
  public int JJTADC = 14;
  public int JJTADCS = 15;
  public int JJTADCC = 16;
  public int JJTADCCS = 17;
  public int JJTSUB = 18;
  public int JJTSUBS = 19;
  public int JJTSUBC = 20;
  public int JJTSUBCS = 21;
  public int JJTSBC = 22;
  public int JJTSBCS = 23;
  public int JJTSBCC = 24;
  public int JJTSBCCS = 25;
  public int JJTRSB = 26;
  public int JJTRSBS = 27;
  public int JJTRSBC = 28;
  public int JJTRSBCS = 29;
  public int JJTRSC = 30;
  public int JJTRSCS = 31;
  public int JJTRSCC = 32;
  public int JJTRSCCS = 33;
  public int JJTCMP = 34;
  public int JJTCMPC = 35;
  public int JJTCMN = 36;
  public int JJTCMNC = 37;
  public int JJTTEQ = 38;
  public int JJTTEQC = 39;
  public int JJTTST = 40;
  public int JJTTSTC = 41;
  public int JJTAND = 42;
  public int JJTANDS = 43;
  public int JJTANDC = 44;
  public int JJTANDCS = 45;
  public int JJTBIC = 46;
  public int JJTBICS = 47;
  public int JJTBICC = 48;
  public int JJTBICCS = 49;
  public int JJTEOR = 50;
  public int JJTEORS = 51;
  public int JJTEORC = 52;
  public int JJTEORCS = 53;
  public int JJTORR = 54;
  public int JJTORRS = 55;
  public int JJTORRC = 56;
  public int JJTORRCS = 57;
  public int JJTLDRPRENEG = 58;
  public int JJTLDRPREPOS = 59;
  public int JJTLDRPOSTNEG = 60;
  public int JJTLDRPOSTPOS = 61;
  public int JJTLDRSIMPLE = 62;
  public int JJTLDRBPRENEG = 63;
  public int JJTLDRBPREPOS = 64;
  public int JJTLDRBPOSTNEG = 65;
  public int JJTLDRBPOSTPOS = 66;
  public int JJTLDRBSIMPLE = 67;
  public int JJTLDRHPRENEG = 68;
  public int JJTLDRHPREPOS = 69;
  public int JJTLDRHPOSTNEG = 70;
  public int JJTLDRHPOSTPOS = 71;
  public int JJTLDRHSIMPLE = 72;
  public int JJTLDRSPRENEG = 73;
  public int JJTLDRSPREPOS = 74;
  public int JJTLDRSPOSTNEG = 75;
  public int JJTLDRSPOSTPOS = 76;
  public int JJTLDRSSIMPLE = 77;
  public int JJTLDRSHPRENEG = 78;
  public int JJTLDRSHPREPOS = 79;
  public int JJTLDRSHPOSTNEG = 80;
  public int JJTLDRSHPOSTPOS = 81;
  public int JJTLDRSHSIMPLE = 82;
  public int JJTLDRSBPRENEG = 83;
  public int JJTLDRSBPREPOS = 84;
  public int JJTLDRSBPOSTNEG = 85;
  public int JJTLDRSBPOSTPOS = 86;
  public int JJTLDRSBSIMPLE = 87;
  public int JJTSTRPRENEG = 88;
  public int JJTSTRPREPOS = 89;
  public int JJTSTRPOSTNEG = 90;
  public int JJTSTRPOSTPOS = 91;
  public int JJTSTRSIMPLE = 92;
  public int JJTSTRBPRENEG = 93;
  public int JJTSTRBPREPOS = 94;
  public int JJTSTRBPOSTNEG = 95;
  public int JJTSTRBPOSTPOS = 96;
  public int JJTSTRBSIMPLE = 97;
  public int JJTSTRHPRENEG = 98;
  public int JJTSTRHPREPOS = 99;
  public int JJTSTRHPOSTNEG = 100;
  public int JJTSTRHPOSTPOS = 101;
  public int JJTSTRHSIMPLE = 102;
  public int JJTSTRSPRENEG = 103;
  public int JJTSTRSPREPOS = 104;
  public int JJTSTRSPOSTNEG = 105;
  public int JJTSTRSPOSTPOS = 106;
  public int JJTSTRSSIMPLE = 107;
  public int JJTSTRSHPRENEG = 108;
  public int JJTSTRSHPREPOS = 109;
  public int JJTSTRSHPOSTNEG = 110;
  public int JJTSTRSHPOSTPOS = 111;
  public int JJTSTRSHSIMPLE = 112;
  public int JJTSTRSBPRENEG = 113;
  public int JJTSTRSBPREPOS = 114;
  public int JJTSTRSBPOSTNEG = 115;
  public int JJTSTRSBPOSTPOS = 116;
  public int JJTSTRSBSIMPLE = 117;
  public int JJTCLOSEAUP = 118;
  public int JJTCLOSE = 119;
  public int JJTSHIFTLS = 120;
  public int JJTSHIFTF = 121;
  public int JJTBCOND = 122;
  public int JJTHCOND = 123;
  public int JJTCOND = 124;
  public int JJTSCND = 125;
  public int JJTLSL = 126;
  public int JJTLSR = 127;
  public int JJTSHIFT = 128;
  public int JJTREGISTER = 129;
  public int JJTNUMBER = 130;
  public int JJTHEXA = 131;
  public int JJTNUM = 132;


  public String[] jjtNodeName = {
    "prog",
    "void",
    "decl",
    "declS",
    "declC",
    "declCS",
    "decln",
    "declnS",
    "declnC",
    "declnCS",
    "add",
    "addS",
    "addC",
    "addCS",
    "adc",
    "adcS",
    "adcC",
    "adcCS",
    "sub",
    "subS",
    "subC",
    "subCS",
    "sbc",
    "sbcS",
    "sbcC",
    "sbcCS",
    "rsb",
    "rsbS",
    "rsbC",
    "rsbCS",
    "rsc",
    "rscS",
    "rscC",
    "rscCS",
    "cmp",
    "cmpC",
    "cmn",
    "cmnC",
    "teq",
    "teqC",
    "tst",
    "tstC",
    "and",
    "andS",
    "andC",
    "andCS",
    "bic",
    "bicS",
    "bicC",
    "bicCS",
    "eor",
    "eorS",
    "eorC",
    "eorCS",
    "orr",
    "orrS",
    "orrC",
    "orrCS",
    "ldrPreNeg",
    "ldrPrePos",
    "ldrPostNeg",
    "ldrPostPos",
    "ldrSimple",
    "ldrBPreNeg",
    "ldrBPrePos",
    "ldrBPostNeg",
    "ldrBPostPos",
    "ldrBSimple",
    "ldrHPreNeg",
    "ldrHPrePos",
    "ldrHPostNeg",
    "ldrHPostPos",
    "ldrHSimple",
    "ldrSPreNeg",
    "ldrSPrePos",
    "ldrSPostNeg",
    "ldrSPostPos",
    "ldrSSimple",
    "ldrSHPreNeg",
    "ldrSHPrePos",
    "ldrSHPostNeg",
    "ldrSHPostPos",
    "ldrSHSimple",
    "ldrSBPreNeg",
    "ldrSBPrePos",
    "ldrSBPostNeg",
    "ldrSBPostPos",
    "ldrSBSimple",
    "strPreNeg",
    "strPrePos",
    "strPostNeg",
    "strPostPos",
    "strSimple",
    "strBPreNeg",
    "strBPrePos",
    "strBPostNeg",
    "strBPostPos",
    "strBSimple",
    "strHPreNeg",
    "strHPrePos",
    "strHPostNeg",
    "strHPostPos",
    "strHSimple",
    "strSPreNeg",
    "strSPrePos",
    "strSPostNeg",
    "strSPostPos",
    "strSSimple",
    "strSHPreNeg",
    "strSHPrePos",
    "strSHPostNeg",
    "strSHPostPos",
    "strSHSimple",
    "strSBPreNeg",
    "strSBPrePos",
    "strSBPostNeg",
    "strSBPostPos",
    "strSBSimple",
    "closeAUp",
    "close",
    "shiftLS",
    "shiftF",
    "bCond",
    "hCond",
    "cond",
    "scnd",
    "lsl",
    "lsr",
    "shift",
    "register",
    "number",
    "hexa",
    "num",
  };
}
/* JavaCC - OriginalChecksum=7f81c2c7e3ca64c02b02d26a2b77026c (do not edit this line) */
